insiderBug/src/Entity/Commentaire.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentaireRepository")
 */
class Commentaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contenu;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $auteur;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_ajout;

    /**
     * @ORM\Column(type="integer")
     */
    private $count_like;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->auteur;
    }

    public function setAuteur(string $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): self
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }

    public function getCountLike(): ?int
    {
        return $this->count_like;
    }

    public function setCountLike(int $count_like): self
    {
        $this->count_like = $count_like;

        return $this;
    }
}

insiderBug/src/Form/CommentaireType.php
<?php

namespace App\Form;

use App\Entity\Commentaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('contenu')
            ->add('auteur')
            ->add('date_ajout')
            ->add('count_like')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commentaire::class,
        ]);
    }
}

insiderBug/src/Controller/CommentaireController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\CommentaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/commentaire")
 */
class CommentaireController extends AbstractController
{
    /**
     * @Route("/", name="commentaire_index", methods="GET")
     */
    public function index(CommentaireRepository $commentaireRepository): Response
    {
        return $this->render('commentaire/index.html.twig', ['commentaires' => $commentaireRepository->findAll()]);
    }

    /**
     * @Route("/new", name="commentaire_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($commentaire);
            $em->flush();

            return $this->redirectToRoute('commentaire_index');
        }

        return $this->render('commentaire/new.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commentaire_show", methods="GET")
     */
    public function show(Commentaire $commentaire): Response
    {
        return $this->render('commentaire/show.html.twig', ['commentaire' => $commentaire]);
    }

    /**
     * @Route("/{id}/edit", name="commentaire_edit", methods="GET|POST")
     */
    public function edit(Request $request, Commentaire $commentaire): Response
    {
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('commentaire_index', ['id' => $commentaire->getId()]);
        }

        return $this->render('commentaire/edit.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commentaire_delete", methods="DELETE")
     */
    public function delete(Request $request, Commentaire $commentaire): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentaire->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($commentaire);
            $em->flush();
        }

        return $this->redirectToRoute('commentaire_index');
    }
}

insiderBug/templates/commentaire/_delete_form.html.twig
<form method="post" action="{{ path('commentaire_delete', {'id': commentaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.id) }}">
    <button class="btn">Delete</button>
</form>

insiderBug/templates/commentaire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

insiderBug/templates/commentaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commentaire{% endblock %}

{% block body %}
    <h1>Edit Commentaire</h1>

    {{ include('commentaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('commentaire_index') }}">back to list</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}

insiderBug/templates/commentaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire index{% endblock %}

{% block body %}
    <h1>Commentaire index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Contenu</th>
                <th>Auteur</th>
                <th>Date_ajout</th>
                <th>Count_like</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commentaire in commentaires %}
            <tr>
                <td>{{ commentaire.id }}</td>
                <td>{{ commentaire.contenu }}</td>
                <td>{{ commentaire.auteur }}</td>
                <td>{{ commentaire.dateAjout ? commentaire.dateAjout|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commentaire.countLike }}</td>
                <td>
                    <a href="{{ path('commentaire_show', {'id': commentaire.id}) }}">show</a>
                    <a href="{{ path('commentaire_edit', {'id': commentaire.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('commentaire_new') }}">Create new</a>
{% endblock %}

insiderBug/templates/commentaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commentaire{% endblock %}

{% block body %}
    <h1>Create new Commentaire</h1>

    {{ include('commentaire/_form.html.twig') }}

    <a href="{{ path('commentaire_index') }}">back to list</a>
{% endblock %}

insiderBug/templates/commentaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire{% endblock %}

{% block body %}
    <h1>Commentaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commentaire.id }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ commentaire.contenu }}</td>
            </tr>
            <tr>
                <th>Auteur</th>
                <td>{{ commentaire.auteur }}</td>
            </tr>
            <tr>
                <th>Date_ajout</th>
                <td>{{ commentaire.dateAjout ? commentaire.dateAjout|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Count_like</th>
                <td>{{ commentaire.countLike }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('commentaire_index') }}">back to list</a>

    <a href="{{ path('commentaire_edit', {'id': commentaire.id}) }}">edit</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}